name: Main

on: push

jobs:
  build:
    strategy:
      matrix:
        rust: [nightly]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v1
    - name: Components
      run: rustup component add clippy
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Run tests
      run: cargo test --verbose